export const itemNames = [
    "DVR / NVR Central", "Câmeras de frente de loja / cofres", "Sensores de presença / alarme",
    "Câmeras externas / perímetro", "QGBT / Quadro geral", "Disjuntores / barramentos",
    "Iluminação de área de vendas", "Iluminação externa / decorativa", "Rack de compressores / unidade condensadora",
    "Evaporadores / câmaras frias", "Condensadoras / expositores", "Splits administrativos",
    "Gerador principal", "Quadro de transferência automática (QTA)", "Nobreak central / retificador",
    "Baterias de reserva / banco de energia", "Bomba de recalque / pressurização", "Reservatórios / caixa d’água",
    "Torneiras / válvulas / sifões", "Elevador / monta-carga", "Portas corta-fogo / hidrantes / exaustores",
    "Estruturas / revestimentos / pisos", "Serra fita", "Câmara fria / balcão refrigerado",
    "Moedor / picador / fatiador", "Embaladora / seladora", "Forno combinado / fritadeira industrial",
    "Estufa quente / expositor", "Coifa / exaustor industrial", "Forno turbo / esteira",
    "Amassadeira / batedeira", "Seladora / balança produção", "Câmaras de climatização / umidificadores",
    "Balcões refrigerados", "Nebulizadores / ventiladores", "Portas automáticas de doca",
    "Lavadora de piso", "Enceradeira / aspirador industrial", "Cancela automática",
    "Iluminação de estacionamento", "Portões automáticos / pedonais", "Climatizador / exaustor",
    "Iluminação / instalações elétricas", "Equipamentos de cozinha / micro-ondas", "Painéis LED / letreiros",
    "Iluminação decorativa / fachadas"
];

export const itemCategoryMap: Record<string, string> = {
    "DVR / NVR Central": "Segurança / CFTV / Alarme",
    "Câmeras de frente de loja / cofres": "Segurança / CFTV / Alarme",
    "Sensores de presença / alarme": "Segurança / CFTV / Alarme",
    "Câmeras externas / perímetro": "Segurança / CFTV / Alarme",
    "QGBT / Quadro geral": "Elétrica / Iluminação",
    "Disjuntores / barramentos": "Elétrica / Iluminação",
    "Iluminação de área de vendas": "Elétrica / Iluminação",
    "Iluminação externa / decorativa": "Elétrica / Iluminação",
    "Rack de compressores / unidade condensadora": "Refrigeração / Climatização Central",
    "Evaporadores / câmaras frias": "Refrigeração / Climatização Central",
    "Condensadoras / expositores": "Refrigeração / Climatização Central",
    "Splits administrativos": "Refrigeração / Climatização Central",
    "Gerador principal": "Energização / Geradores / Nobreaks",
    "Quadro de transferência automática (QTA)": "Energização / Geradores / Nobreaks",
    "Nobreak central / retificador": "Energização / Geradores / Nobreaks",
    "Baterias de reserva / banco de energia": "Energização / Geradores / Nobreaks",
    "Bomba de recalque / pressurização": "Hidráulica / Utilidades",
    "Reservatórios / caixa d’água": "Hidráulica / Utilidades",
    "Torneiras / válvulas / sifões": "Hidráulica / Utilidades",
    "Elevador / monta-carga": "Infraestrutura Predial",
    "Portas corta-fogo / hidrantes / exaustores": "Infraestrutura Predial",
    "Estruturas / revestimentos / pisos": "Infraestrutura Predial",
    "Serra fita": "Açougue / Frios",
    "Câmara fria / balcão refrigerado": "Açougue / Frios",
    "Moedor / picador / fatiador": "Açougue / Frios",
    "Embaladora / seladora": "Açougue / Frios",
    "Forno combinado / fritadeira industrial": "Rotisserie / Cozinha",
    "Estufa quente / expositor": "Rotisserie / Cozinha",
    "Coifa / exaustor industrial": "Rotisserie / Cozinha",
    "Forno turbo / esteira": "Padaria / Confeitaria",
    "Amassadeira / batedeira": "Padaria / Confeitaria",
    "Seladora / balança produção": "Padaria / Confeitaria",
    "Câmaras de climatização / umidificadores": "Padaria / Confeitaria",
    "Balcões refrigerados": "Hortifrúti / Floricultura",
    "Nebulizadores / ventiladores": "Hortifrúti / Floricultura",
    "Portas automáticas de doca": "Depósito / Doca",
    "Lavadora de piso": "Limpeza e Apoio",
    "Enceradeira / aspirador industrial": "Limpeza e Apoio",
    "Cancela automática": "Estacionamento / Acessos / Cancelas",
    "Iluminação de estacionamento": "Estacionamento / Acessos / Cancelas",
    "Portões automáticos / pedonais": "Estacionamento / Acessos / Cancelas",
    "Climatizador / exaustor": "Refeitório / Vestiários / Áreas de Apoio ao Colaborador",
    "Iluminação / instalações elétricas": "Refeitório / Vestiários / Áreas de Apoio ao Colaborador",
    "Equipamentos de cozinha / micro-ondas": "Refeitório / Vestiários / Áreas de Apoio ao Colaborador",
    "Painéis LED / letreiros": "Logo/ Painéis / Iluminação decorativa",
    "Iluminação decorativa / fachadas": "Logo/ Painéis / Iluminação decorativa"
};
