import { UserRole } from './types';

export type ModuleDefinition = {
  id: string;
  label: string;
};

export const roleList: UserRole[] = ['admin', 'gestor', 'regional', 'visualizador', 'fornecedor', 'usuario'];

export const moduleDefinitions: ModuleDefinition[] = [
  { id: 'indicators', label: 'Painel de Indicadores' },
  { id: 'releases', label: 'LanÃ§amentos Mensais' },
  { id: 'incidents', label: 'Registro de Incidentes' },
  { id: 'rncs', label: 'Registros de NÃ£o Conformidade' },
  { id: 'laudos', label: 'Gerar Laudo TÃ©cnico' },
  { id: 'categories', label: 'Categorias de Itens' },
  { id: 'matrix', label: 'Matriz de Itens' },
  { id: 'compliance', label: 'Cronograma de Preventivas' },
  { id: 'suppliers', label: 'GestÃ£o de Fornecedores' },
  { id: 'warranty', label: 'Controle de Garantias' },
  { id: 'tools', label: 'Almoxarifado de Ferramentas' },
  { id: 'assets', label: 'GestÃ£o de Ativos' },
  { id: 'vacations', label: 'GestÃ£o de FÃ©rias' },
  { id: 'settlement', label: 'Cartas de QuitaÃ§Ã£o' },
  { id: 'escopos', label: 'CriaÃ§Ã£o de Escopos' },
  { id: 'dataQuality', label: 'ObservatÃ³rio de Dados' },
  { id: 'actionBoard', label: 'Quadro de AÃ§Ãµes' },
  { id: 'aiChat', label: 'Chat Tecnico com IA' },
  { id: 'aiInsights', label: 'Insights do Assistente AI' },
  { id: 'integrations', label: 'Painel de IntegraÃ§Ãµes' },
  { id: 'profile', label: 'Meu Perfil' },
  { id: 'settings', label: 'ConfiguraÃ§Ãµes' },
  { id: 'about', label: 'Sobre a Plataforma' },
  { id: 'users', label: 'UsuÃ¡rios' },
  { id: 'administration', label: 'AdministraÃ§Ã£o' },
  { id: 'admin-dashboard', label: 'Dashboard Global (Admin)' },
  { id: 'admin-users', label: 'UsuÃ¡rios e PapÃ©is' },
  { id: 'admin-integrations', label: 'IntegraÃ§Ãµes e API' },
  { id: 'admin-modules', label: 'MÃ³dulos e Flags' },
  { id: 'admin-analytics', label: 'MÃ©tricas e Acessos' },
  { id: 'admin-audit', label: 'Auditoria' },
  { id: 'admin-config', label: 'ConfiguraÃ§Ãµes do Sistema' },
  { id: 'admin-health', label: 'Healthcheck' },
  { id: 'admin-roles', label: 'PapÃ©is e RBAC' },
];

const adminPermissions = Object.fromEntries(moduleDefinitions.map(m => [m.id, true]));

const defaultRolePermissions: Record<UserRole, Record<string, boolean>> = {
  // keep admin explicit (all modules enabled)
  admin: { ...adminPermissions, vacations: true },
  gestor: {
    indicators: true,
    releases: true,
    incidents: true,
    rncs: true,
    categories: true,
    matrix: true,
    compliance: true,
    suppliers: true,
    warranty: true,
    tools: true,
    assets: true,
    settlement: true,
    vacations: true,
    escopos: true,
    dataQuality: true,
    actionBoard: true,
    aiChat: true,
    aiInsights: true,
    integrations: true,
    profile: true,
    settings: true,
    about: true,
    users: true,
    administration: false,
    'admin-dashboard': true,
    'admin-users': true,
    'admin-modules': true,
    'admin-analytics': true,
    'admin-audit': true,
    'admin-config': true,
    'admin-health': true,
    'admin-roles': true,
    'admin-integrations': true,
  },
  regional: {
    indicators: true,
    releases: false,
    incidents: true,
    rncs: true,
    categories: false,
    matrix: true,
    compliance: true,
    suppliers: false,
    warranty: true,
    tools: true,
    assets: true,
    settlement: false,
    vacations: false,
    escopos: true,
    dataQuality: true,
    actionBoard: true,
    aiChat: true,
    aiInsights: true,
    integrations: true,
    profile: true,
    settings: true,
    about: true,
    users: false,
    administration: false,
    'admin-dashboard': false,
    'admin-users': false,
    'admin-modules': false,
    'admin-analytics': false,
    'admin-audit': false,
    'admin-config': false,
    'admin-health': false,
    'admin-roles': false,
    'admin-integrations': false,
  },
  visualizador: {
    indicators: true,
    releases: false,
    incidents: false,
    rncs: false,
    categories: false,
    matrix: false,
    compliance: false,
    suppliers: false,
    warranty: false,
    tools: false,
    assets: false,
    settlement: false,
    vacations: false,
    escopos: false,
    dataQuality: true,
    actionBoard: true,
    aiChat: true,
    aiInsights: true,
    integrations: true,
    profile: true,
    settings: false,
    about: true,
    users: false,
    administration: false,
    'admin-dashboard': false,
    'admin-users': false,
    'admin-modules': false,
    'admin-analytics': false,
    'admin-audit': false,
    'admin-config': false,
    'admin-health': false,
    'admin-roles': false,
    'admin-integrations': false,
  },
  fornecedor: {
    indicators: false,
    releases: false,
    incidents: false,
    rncs: false,
    categories: false,
    matrix: false,
    compliance: false,
    suppliers: false,
    warranty: false,
    tools: false,
    assets: false,
    settlement: true,
    vacations: false,
    escopos: false,
    dataQuality: true,
    actionBoard: false,
    aiChat: true,
    aiInsights: true,
    integrations: false,
    profile: true,
    settings: true,
    about: true,
    users: false,
    administration: false,
    'admin-dashboard': false,
    'admin-users': false,
    'admin-modules': false,
    'admin-analytics': false,
    'admin-audit': false,
    'admin-config': false,
    'admin-health': false,
    'admin-roles': false,
    'admin-integrations': false,
  },
  usuario: {
    indicators: true,
    releases: false,
    incidents: false,
    rncs: false,
    categories: false,
    matrix: false,
    compliance: false,
    suppliers: false,
    warranty: false,
    tools: false,
    assets: false,
    settlement: false,
    vacations: false,
    escopos: false,
    dataQuality: true,
    actionBoard: true,
    aiChat: true,
    aiInsights: true,
    integrations: true,
    profile: true,
    settings: true,
    about: true,
    users: false,
    administration: false,
    'admin-dashboard': false,
    'admin-users': false,
    'admin-modules': false,
    'admin-analytics': false,
    'admin-audit': false,
    'admin-config': false,
    'admin-health': false,
    'admin-roles': false,
    'admin-integrations': false,
  },
};

export function cloneDefaultPermissions(): Record<UserRole, Record<string, boolean>> {
  const copy: Record<UserRole, Record<string, boolean>> = {} as any;
  roleList.forEach(role => {
    copy[role] = { ...(defaultRolePermissions[role] ?? {}) };
  });
  return copy;
}

