# Generates stores-update-latlng.sql from API /api/stores
$stores = Invoke-RestMethod -Uri 'http://localhost:9002/api/stores' -Method Get
$out = 'stores-update-latlng.sql'
"-- SQL update script generated by generate-sql-from-stores.ps1 on $(Get-Date -Format o)" | Out-File $out -Encoding UTF8
"BEGIN;" | Add-Content $out
foreach ($s in $stores) {
    $id = ($s.id -as [string]) -replace "'","''"
    if ($null -eq $s.lat -or $s.lat -eq 0) { $lat = 'NULL' } else { $lat = ([string]$s.lat) -replace ',', '.' }
    if ($null -eq $s.lng -or $s.lng -eq 0) { $lng = 'NULL' } else { $lng = ([string]$s.lng) -replace ',', '.' }
    $line = "UPDATE stores SET lat = $lat, lng = $lng WHERE id = '$id';"
    $line | Add-Content $out
}
"COMMIT;" | Add-Content $out
Write-Output "WROTE: $out (rows=$($stores.Count))"
