BEGIN;

-- Add missing columns to `tools` table used by the app
ALTER TABLE tools ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE tools ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE tools ADD COLUMN IF NOT EXISTS serial_number TEXT;
ALTER TABLE tools ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Disponível';
ALTER TABLE tools ADD COLUMN IF NOT EXISTS assigned_to TEXT;
ALTER TABLE tools ADD COLUMN IF NOT EXISTS purchase_date DATE;
ALTER TABLE tools ADD COLUMN IF NOT EXISTS last_maintenance TIMESTAMPTZ;
ALTER TABLE tools ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now();

COMMIT;
